### PR TITLE
Move pwndbg/{heap,disasm} into gdblib

### PR DESCRIPTION
**Pull request by mbrla0**
This is part of the work being done for the GSoC 2024 LLDB Port, tracked by #2204.

This PR moves both `pwndbg.heap` and `pwndbg.disasm` into `pwndbg.gdblib`, given their current heavy reliance on `gdblib`. This is intended to facilitate bringing up Pwndbg under LLDB, as part of making it easier to spot and isolate stray `gdblib` imports and calls.

Later on, as we add more and more of the things these modules need to the debugger-agnostic API, it will probably make sense to take the non-debugger-specific bits back out of `gdblib`, but that's still in the future.

### CODE REVIEW

**Comment by gsingh93** [comment]
@mbrla0 can you run `./lint.sh -f`?

**Comment by gsingh93** [comment]
@CptGibbon FYI, the heap folder is moving.

**Comment by CptGibbon** [comment]
> @CptGibbon FYI, the heap folder is moving.

Ack.
CC: @lebr0nli @jetchirag

**Comment by mbrla0** [comment]
> @mbrla0 can you run `./lint.sh -f`?

I had, and apparently `ruff` had failed to run and I didn't notice it. That part should be fixed now. But mypy's still complaining, so I'll get on it.

**Comment by gsingh93** [comment]
Needs a rebase, but otherwise LGTM.

Also FYI @OBarronCS, the disasm folder is moving.

**Pull request merged**
