### PR TITLE
[heap] `hi` command -- feature to check if an address belongs to a chunk.

### PR DESCRIPTION
**Pull request by kotee4ko**
As a RC version of https://github.com/pwndbg/pwndbg/pull/1761

### CODE REVIEW

**Comment by disconnect3d** [comment]
Should we close #1761 then? :)
Also this needs a fix for the lint part :P

**Comment by kotee4ko** [comment]
@disconnect3d  done

**Comment by disconnect3d** [comment]
Just one very last thing: should we rename this to `heapinclude` or `ischunk`? cc: @CptGibbon

**Comment by disconnect3d** [comment]
btw @kotee4ko "This branch cannot be rebased due to conflicts" :(

**Comment by kotee4ko** [comment]
> btw @kotee4ko "This branch cannot be rebased due to conflicts" :(


Emmm..
```
This branch has no conflicts with the base branch
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
```

Am I missing something?

**Comment by disconnect3d** [comment]
Hmm: 
image

Not sure why this happens. I'll look at this deeper in the evening/tomorrow.

**Review by disconnect3d — APPROVED** [review]

**Pull request merged**
