### PR TITLE
Malloc chunk dump

### LINKED ISSUE #1238: Add support to malloc_chunk for dumping the entire chunk, including the data
It would be useful if there was a flag for `malloc_chunk` (maybe `--dump`?) that would print a hexdump of the chunk bytes after printing the chunk header information. This would allow me to see all the information about a chunk and its data in a single command, without needing to calculate how many bytes to dump myself.

### PR DESCRIPTION
**Pull request by jetchirag**
Fixes #1238 

Screenshot:

image

### CODE REVIEW

**Review by disconnect3d — COMMENTED** [review]
@CptGibbon The changes looks good to me; pls see if the `chunk.real_address` is correct here and if so, lets merge?

It would be nice if a test was added for this if its possible ;)

**Comment by jetchirag** [comment]
@disconnect3d Do you mean `real_size`? Check my last commit, made changes as per discussion on discord. I'll add tests next.

**Comment by disconnect3d** [comment]
Yeah I meant `real_size`*, my bad :)

**Comment by CptGibbon** [comment]
Never believe anyone who says "I'll add tests later" 😆 but yeah this looks good 👍

**Comment by jetchirag** [comment]
> Never believe anyone who says "I'll add tests later" 😆 but yeah this looks good 👍

Added 😁

**Comment by CptGibbon** [comment]
Thanks 🙏
I'll review this next week.

**Review by CptGibbon — APPROVED** [review]
I think this looks good, thanks for the PR 🙏
I'm happy for this to be merged if there are no objections.

image

How will this interact with #2098?

**Comment by jetchirag** [comment]
> How will this interact with #2098?

Ah, they won't work well together. I'll open another PR for it once both are merged. Or we can merge this first and I'll add that to next flag PR.

**Comment by jetchirag** [comment]
Tests are failing but I think error is unrelated
> line 1: docker-compose: command not found

**Comment by disconnect3d** [comment]
For some reason GH keeps saying:
> Checking for ability to merge automatically…
> Hang in there while we check the branch’s status.

weird

**Comment by disconnect3d** [comment]
Thanks! Pls add support for `--dump --next` in next PR

**Comment by jetchirag** [comment]
> Thanks! Pls add support for `--dump --next` in next PR

It should already be included in this PR. Check commit [fde640b](https://github.com/pwndbg/pwndbg/pull/2085/commits/fde640b1e72f68642a8ff245d3f6110b53811356)

**Pull request merged**
