### PR TITLE
Added next flag to malloc_chunk

### LINKED ISSUE #2086: Next flag for malloc_chunk
Opening this FR related to #1059. I don't think this was later implemented so I want to pick this up to get more familiar with codebase.

> Why stop at the next chunk? The chunk after that can be just as important, as can the previous chunk. Maybe a flag that lets you print a user-defined number of next/previous/surrounding chunks would be useful.

I was however wondering on the way to go about flags. Should we keep 3 seperate flags similar to grep (A, B for next, prev and C for surrounding) or just the next X chunks e.g. `--next 3`?

### PR DESCRIPTION
**Pull request by jetchirag**
Fixes #2086

- [ ] Add test

### CODE REVIEW

**Review by CptGibbon — CHANGES_REQUESTED** [review]
Looks great, thank you very much for this PR 🙏

Screenshot 2024-03-27 at 11 14 56

My personal opinion: it could be useful to print _both_ the chunk at the address passed and its succeeding chunks, that way you don't have to run the command twice to see all that information.

@gsingh93 was that what you had in mind originally in #1059?

If so, the loop for printing next chunks could perhaps be moved after the initial printing code.

**Comment by jetchirag** [comment]
@CptGibbon That makes sense and how I originally wrote it but original PR seemed to hint at just next chunks. Let me know if I should move the loop to end.

**Comment by disconnect3d** [comment]
Yeah lets show both the chunk and the next chunks

**Comment by CptGibbon** [comment]
I'll review this again next week 👍

**Review by CptGibbon — APPROVED** [review]
Looks great 👍
Thanks for this PR, I'm happy for it to get merged if there are no objections.

Screenshot 2024-04-01 at 21 03 41

**Pull request merged**
