### PR TITLE
early exit when require a valid file to be selected

### PR DESCRIPTION
**Pull request by anthraxx**

### CODE REVIEW

**Comment by zachriggle** [comment]
I like this, but I'd prefer to have a bit more info and stick closer to GDB's default error messages.  Can we replace our message with whatever is printed when eg "info file" is done without a file selected?

**Comment by anthraxx** [comment]
sure, can see i just tried to stick to what was used in multiple places already

**Comment by anthraxx** [comment]
Hm it just silently does nothing (which actually i don't like too much :yum:)

**Comment by zachriggle** [comment]
Ha, that's funny. Can we at least add a "See 'help file' for more
information." at the end?

**Comment by anthraxx** [comment]
sure that sounds appropriate. as i don't want to duplicate that all over the place, i will create a error string that we can reference globally

**Comment by zachriggle** [comment]
Good plan! Now add i18n! (Just kidding)

**Comment by zachriggle** [comment]
Merging this for now, we can add the string error thing later

**Pull request merged**
