### PR TITLE
checksec: cache output of command

### PR DESCRIPTION
**Pull request by bennofs**
I think the wrapper updates were meant to include this but it seems they don't?

### CODE REVIEW

**Comment by disconnect3d** [comment]
Thanks for PR! Yeah, we meant to cache it. I must have missed it during review.

Can we actually simplify it a bit more? I mean, there is `get_raw_out` which turns out (by a fast `git grep get_raw_out` so it isn't 100% accurately) to be not used anywhere at all.

I guess it was intended to be used in both `relro_status` and `pie_status` as they actually duplicate its logic.

So... just call it there :).

**Comment by degrigis** [comment]
ops, my fault, sorry for that :-) 
However `get_raw_out` is used inside the command `chekcsec` ( /pwndbg/commands/checksec.py ).

**Comment by disconnect3d** [comment]
@bennofs Bump

**Comment by bennofs** [comment]
@disconnect3d oops sorry forgot about it. should be ok now

**Comment by disconnect3d** [comment]
@bennofs Thanks!

**Pull request merged**
