### PR TITLE
Fixed GDB remote get command

### PR DESCRIPTION
**Pull request by reu-res**

### CODE REVIEW

**Comment by zachriggle** [comment]
I expect that this simple quoting won't guarantee that the issue is fixed.

Can you provide a test-case where this failed?  I expect we have a need for a `sh_string` equivalent which generates GDB-compatible escaped strings.

**Comment by reu-res** [comment]
Before patch
image

After patch
image

**Comment by zachriggle** [comment]
I definitely understand that this fixes your specific issue.  However, while we're taking the time to fix this, I'd prefer to fix it once, in a reusable manner, and permanently.  Do we know how unprintable characters and embedded quotes work on the GDB command-line?

**Comment by zachriggle** [comment]
Please re-target this against the `dev` branch <3

**Pull request closed without merging**
