### PR TITLE
leakfind should default to $sp

### LINKED ISSUE #1210: `leakfind` should default to `$sp`
The first argument to `leakfind` is required, but it should just default to `$sp` like `probeleak` does.

### PR DESCRIPTION
**Pull request by amoghrajesh**
Fixes #1210 

Raising the PR to "dev" branch.

### CODE REVIEW

**Comment by amoghrajesh** [comment]
@gsingh93 I am unable to figure out why the lint is failing too. Could you help? The logs are not so informative

**Comment by gsingh93** [comment]
Thanks! Just FYI, you can run `./lint.sh` locally to see the lint errors, and `./lint.sh -f` will attempt to fix any errors it can.

**Comment by disconnect3d** [comment]
Is this really working? I think that `$sp` string will fail here on `int(address)`

**Comment by gsingh93** [comment]
I tested it locally and it worked. And it's the same as what `probeleak` is doing, and that works as well.

**Pull request merged**
