### PR TITLE
Add ipython as a dependency

### PR DESCRIPTION
**Pull request by gsingh93**

### CODE REVIEW

**Comment by gsingh93** [comment]
@disconnect3d idk how to fix this lock file issue :( can we document what to do in the dev docs?

**Comment by disconnect3d** [comment]
cc: @patryk4815 can u remind us how to fix that? :D

**Comment by patryk4815** [comment]
fixed in: https://github.com/pwndbg/pwndbg/pull/2052

**Comment by disconnect3d** [comment]
@gsingh93 I think this now misses the installation of ipython?

**Pull request merged**
