### PR TITLE
GDB Refactor [1/N]: Split arch.py and related files into lib/ and gdb/

### PR DESCRIPTION
**Pull request by gsingh93**
This PR starts refactoring GDB dependent code into `gdb/` and non-GDB dependent code into `lib/`. This will make writing code and testing easier.

In this PR parts of `arch.py` are moved to `lib/arch.py`, and a few included files like `tempfile.py` and `memoize.py` were also moved. `lib/arch.py` also implements a new class `Arch`, which will also make testing easier in the future.

`typeinfo.py` and parts of `arch.py` where moved to `gdb/`.

Finally, `gdb/hooks.py` is a new file that will consolidate all of the trivial hooks, such as the arch, typeinfo, and memoize hooks which only call a single function in `lib`.

### CODE REVIEW

**Comment by syheliel** [comment]
The directory gdb causes some confusion with the original gdb package. maybe rename it as gdblib or gdbwrapper?

**Comment by gsingh93** [comment]
Rebased on the latest `dev`.

I'm fine with `gdblib`. @disconnect3d?

**Comment by disconnect3d** [comment]
@gsingh93 can u rebase on top of latest dev?

**Comment by gsingh93** [comment]
Done. Would you like me to keep the `pwndbg.gdb` name in the current PR or update it to `pwndbg.gdblib`?

**Comment by disconnect3d** [comment]
Yeah, gdblib is fine

**Comment by gsingh93** [comment]
Done.

Edit: oops, forgot to run isort/black

**Comment by gsingh93** [comment]
Fixed the lint issues.

**Pull request merged**
