### PR TITLE
#664 mark changed registers

### PR DESCRIPTION
**Pull request by layderv**

### CODE REVIEW

**Comment by layderv** [comment]
You can see in https://travis-ci.org/github/pwndbg/pwndbg/jobs/685898957 the build is failing. I've added a commit to fix it as well. I can remove/split it, if it's unnecessary.

**Comment by zachriggle** [comment]
Can we remove the `trusty` -> `bionic` change from this?  We should do that separately from this PR.

**Comment by layderv** [comment]
> Can we remove the `trusty` -> `bionic` change from this? We should do that separately from this PR.

Updated.

**Comment by layderv** [comment]
Do I need to do anything else here? Can this be merged?

**Comment by layderv** [comment]
Any update on this @zachriggle ?

**Comment by disconnect3d** [comment]
Tested it and it works. It will also mark register changes when we switch between threads - I guess this could be improved one way or another but I think it is good enough.

**Pull request merged**
