### PR TITLE
Add __repr__ and __str__ methods to GDBValue

### PR DESCRIPTION
**Pull request by itaysnir**
Fixes issue #2406

### CODE REVIEW

**Comment by mbrla0** [comment]
I actually have a few reservations with this PR as it stands. 

Firstly, when adding things to the Debugger-agnostic API, I personally think it's important to also add an implementation for LLDB. I don't think we want our implementations of the API to be out of sync with each other.

Secondly, the way LLDB and GDB stringify values is very much not consistent between them, and you're choosing to use the format GDB spits out verbatim. This might not be that big of a deal, since I'm not sure we would ever have a reason to want them to be consistent, but, if we ever do, we'd have to either define a standard way to stringify values, or emulate whatever GDB does on the LLDB side, which is a considerable amount of work.

Thirdly, `SBValue` on the LLDB side doesn't have proper useful stringification that we can easily (and quickly) tap into, as far as I know, the closest it has is a `__repr__` implementation that isn't exactly friendly-looking or good to read in situations like the one in #2406. How would we have the output of `__str__` be useful there? Would we have to handle different types of values differently in the LLDB backend, all manually?

In fact, when I was writing the Debugger-agnostic API, I chose not to have `__str__` in `pwndbg.dbg.Value` because of the last two issues.

Personally, to fix #2406 I would go for changing the `__str__` method in `pwndbg.aglib.heap.structs.CStruct2GDB` instead, since that's where the problem is coming from, and we know that class only uses `int`'s anyway, and `pwndbg.dbg.Value` has an `__int__` implementation. But I feel like @disconnect3d should probably weigh in on this.

**Comment by CptGibbon** [comment]
IMO an acceptable stopgap while pwndbg moves away from using debugger-specific classes like `GDBValue`

**Comment by mbrla0** [comment]
> IMO an acceptable stopgap while pwndbg moves away from using debugger-specific classes like `GDBValue`

I don't know if I understand what you mean? We're not moving away from `GDBValue` at all. It's the value class in the GDB imeplmentation of the the Debugger-agnostic API. The one that implements all of the parts of Value that have to talk to GDB - like querying types, doing casts, doing derefs, etc. - when we're running under GDB.

**Comment by itaysnir** [comment]
> s

Thank you for your comment. 
Would wait for @disconnect3d  reply, and I'd implement your suggested approach.

**Comment by CptGibbon** [comment]
> I don't know if I understand what you mean? We're not moving away from `GDBValue` at all. It's the value class in the GDB imeplmentation of the the Debugger-agnostic API. The one that implements all of the parts of Value that have to talk to GDB - like querying types, doing casts, doing derefs, etc. - when we're running under GDB.

It's okay, I know what a GDBValue is.
We're moving away from them pervading every part of pwndbg, e.g. printing values directly from them in a pwndbg command. See #2082 for an example.

This particular case is to do with the cstruct layer for the heap code anyway.

Ping @lebr0nli about the above

**Comment by mbrla0** [comment]
> > > IMO an acceptable stopgap while pwndbg moves away from using debugger-specific classes like `GDBValue`
> > 
> > 
> > I don't know if I understand what you mean? We're not moving away from `GDBValue` at all. It's the value class in the GDB imeplmentation of the the Debugger-agnostic API. The one that implements all of the parts of Value that have to talk to GDB - like querying types, doing casts, doing derefs, etc. - when we're running under GDB.
> 
> It's okay, I know what a GDBValue is. We're moving away from them pervading every part of pwndbg, e.g. printing values directly from them in a pwndbg command. This particular case is to do with the cstuct layer for the heap code anyway.
> 
> Ping @lebr0nli about the above

You're thinking of a `gdb.Value`, `GDBValue`s are something else. `GDBValue`s are implementations of `pwndbg.dbg.Value`, which is the thing we're moving to, and away from `gdb.Value`.

**Comment by disconnect3d** [comment]
Ugh, that sounds really complex for something that looks very simple at first glance :).

I will accept this PR as a quickfix, to make things on dev work as expected, but it seems that @mbrla0 solution is better?

Can you @mbrla0 or @itaysnir revert this PR changes in another PR and implement what @mbrla0 suggested? Can we also add a testcase to confirm that the expected behavior work as expected after the change suggested by @mbrla0 ?

**Comment by itaysnir** [comment]
> Ugh, that sounds really complex for something that looks very simple at first glance :).
> 
> I will accept this PR as a quickfix, to make things on dev work as expected, but it seems that @mbrla0 solution is better?
> 
> Can you @mbrla0 or @itaysnir revert this PR changes in another PR and implement what @mbrla0 suggested? Can we also add a testcase to confirm that the expected behavior work as expected after the change suggested by @mbrla0 ?

Sure, starting to work on this.

**Pull request merged**
