### PR TITLE
In malloc_chunk replace size with real_size

### PR DESCRIPTION
**Pull request by neryaz**
`real_size` is the size of chunk without size bits(PREV_INUSE ,IS_MMAPPED, NON_MAIN_ARENA)

### CODE REVIEW

**Comment by CptGibbon** [comment]
I think there are good arguments for printing both `size` and `real_size` here, since they both convey useful information.
Perhaps adding a "real size" line to the output whilst keeping the "size" line would make everyone happy.

There are also tests that rely on that "size" output, so they'll need a small modification too 👍

**Comment by disconnect3d** [comment]
I agree on printing both. Can we also mention the difference between them in some heap command's `--help` description so that it is more clear/discoverable to the user?

A code comment would also be nice here.

**Comment by disconnect3d** [comment]
@neryaz can u change the PR to display both size and real size? Perhaps we can do it in the same line and write it like: `Size: %#x (real size with flag bits: %#x)`

Also, tests need to be fixed.

**Comment by disconnect3d** [comment]
@neryaz ping

**Comment by disconnect3d** [comment]
I'm going to close this because of lack of activity.

**Pull request closed without merging**
