### PR TITLE
Use inthook only in gdb with Python 2

### PR DESCRIPTION
**Pull request by disconnect3d**
Because of the inthook one can't use OR operation with Python 3 enums:

```
pwndbg> py import re; re.DOTALL | re.MULTILINE
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/enum.py", line 794, in __or__
    result = self.__class__(self._value_ | self.__class__(other)._value_)
  File "/usr/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 760, in _missing_
    new_member = cls._create_pseudo_member_(value)
  File "/usr/lib/python3.6/enum.py", line 786, in _create_pseudo_member_
    pseudo_member._name_ = None
AttributeError: 'int' object has no attribute '_name_'
Error while executing Python code.
```

### CODE REVIEW

**Comment by disconnect3d** [comment]
Just as an information, the problem doesn't occur in gdb with Python 2: https://asciinema.org/a/cl5pjup8o9lpt8w1ue496q4mm

**Comment by disconnect3d** [comment]
This bug is also a blocker for asm syntax highlighting ( https://github.com/anthraxx/pwndbg/tree/feature/syntax-highlight ) developed by @anthraxx .

**Comment by zachriggle** [comment]
The inthook is necessary for Python3 as well

**Comment by disconnect3d** [comment]
@zachriggle Is it? Quick look didn't show any bugs.

Anyway, I have found a solution for this. I will add it in another PR in a moment.

**Comment by disconnect3d** [comment]
Another solution added in PR https://github.com/pwndbg/pwndbg/pull/222.

**Comment by zachriggle** [comment]
@disconnect3d We use the `inthook` to force all invocations `int(gdb.Value object)` to be unsigned longs.  This is not the default behavior.

**Comment by disconnect3d** [comment]
Solution will be merged in PR https://github.com/pwndbg/pwndbg/pull/222.

**Pull request closed without merging**
