### PR TITLE
Bring back possibility of empty context

### PR DESCRIPTION
**Pull request by disconnect3d**
Bringing back the feature we killed in PR 396 - https://github.com/pwndbg/pwndbg/pull/396#issuecomment-359363576

### CODE REVIEW

**Comment by disconnect3d** [comment]
@zachriggle @anthraxx pls a fast review if possible as this is kinda a dev hotfix :P

**Comment by anthraxx** [comment]
Wouldn't a magic value of 'none' be better so one can reset to default values as well?
Just an idea to have more possibilities

**Comment by disconnect3d** [comment]
Yeah I think we can add none too.

27.01.2018 5:39 PM "Levente Polyak" <notifications@github.com> napisał(a):

**Comment by anthraxx** [comment]
well i thought about `none` exlucisbly for disabling context. I think it may be handy to set to the default value when entering no value but at the end i don't care too much. Just find it also loose of posibillities to not being able to use the defaults, whatever that is

**Comment by disconnect3d** [comment]
After last changes all of `''`, `""`, `'empty'`, `none` (case insensitive) set no sections.

**Pull request merged**
