### PR TITLE
Fixes gdb function help text not showing up

### PR DESCRIPTION
**Pull request by k4lizen**
Before:
image

After:
image

### CODE REVIEW

**Comment by k4lizen** [comment]
Lint is enforcing wacky indentation on `hex2ptr` and `bn_eval`:
image

**Comment by patryk4815** [comment]
🤔 Maybe we should strip leading spaces from every line of `self.__doc__`
```py
class _GdbFunction(gdb.Function):
    def __init__(self, func: Callable[..., Any], only_when_running: bool) -> None:
        self.name = func.__name__
        self.func = func
        self.only_when_running = only_when_running
        self.__doc__ = func.__doc__

```

**Comment by disconnect3d** [comment]
Thanks!

Regarding indents/spaces - would have to look at it, but we have multiline docs in commands as well; tho there we use some Argparse magic for that.

**Comment by disconnect3d** [comment]
Anyway, I'd be happy to accept/merge a fix for those indents

**Pull request merged**
