### PR TITLE
Merge dev to stable

### PR DESCRIPTION
**Pull request by disconnect3d**
before release

### CODE REVIEW

**Comment by disconnect3d** [comment]
@zachriggle I can't merge stable without approval :P

**Comment by zachriggle** [comment]
This seems backwards to me.  Why was 'dev' merged into 'stable'?

The 'appropriate' way to do it would be to merge:

    stable --> beta
    beta --> dev

And then update the branches via a fast-forward.

**Comment by disconnect3d** [comment]
> Why was 'dev' merged into 'stable'?

Did you _mean stable merged to dev_ - https://github.com/pwndbg/pwndbg/pull/381? I thought it would be clean to do so, to be 100% sure we have all fixes done to stable on dev.

@zachriggle What do you mean by the arrows? ;D

lets assume dev is on `5390912 - Add capstone, unicorn versions to version command (#379) (2 days ago) <Disconnect3d>` - which it was before I hit `git merge stable` on `dev` and merged it on github (we can `reset --hard && push -f` or `git revert` and make a PR).

What should be done in such case? Is it:
```
git checkout beta
git merge dev

git checkout stable
git merge beta
```
or the other way around? Above commands actually make a conflict when merging beta to stable.

Also, where should hotfixes go? Right way to stable and cherry-pick them on dev or the other way - merge them to dev and cherry-pick on stable?

**Comment by disconnect3d** [comment]
Closing. I am not sure how to deal with that properly atm

**Pull request closed without merging**
