### PR TITLE
fix context showing unexpectedly on first command

### PR DESCRIPTION
**Pull request by lonnywong**

### CODE REVIEW

**Comment by disconnect3d** [comment]
I am not sure I get what it changes :D. Can you show a screen before/after or how can I reproduce the 'bad' behavior?

**Comment by lonnywong** [comment]
> I am not sure I get what it changes :D. Can you show a screen before/after or how can I reproduce the 'bad' behavior?

1. gdb attach to a running process.
2. execute any pwndbg command.

**Comment by disconnect3d** [comment]
If you do: `gdb` and then `attach <pid>` then it does not occur. It occurs in a `gdb -p <pid>` case.

**Comment by disconnect3d** [comment]
I still don't quite understand why this fixes the problem, but it fixes it, so thanks a lot for it! :)

**Comment by lonnywong** [comment]
> I still don't quite understand why this fixes the problem, but it fixes it, so thanks a lot for it! :)

Check the code:
https://github.com/pwndbg/pwndbg/blob/f2e5c98f238320c8a09ef5b472d9116fe7da2640/pwndbg/prompt.py#L50

`*a` make sure it passes as is.

**Pull request merged**
