### PR TITLE
Solving issue #2485

### PR DESCRIPTION
**Pull request by AadishJ**
This PR addresses the issue where the number of passed and skipped tests were not being displayed separately in the test summary. The following changes were made to resolve this issue:

Encapsulation of Test Counters:

Introduced a TestStats class to encapsulate the counters for passed, skipped, and failed tests.
The TestStats class includes methods to handle test results and update the counters accordingly.
Refactoring run_tests_and_print_stats Function:

Modified the run_tests_and_print_stats function to use an instance of the TestStats class.
Updated the function to print the number of passed, skipped, and failed tests separately in the summary.
Improved Code Modularity:

Encapsulating the counters in a class improves code modularity and maintainability.
The handle_test_result method in the TestStats class ensures that the counters are updated correctly and the results are printed in a consistent format.
Changes
Added TestStats class to encapsulate test counters.
Refactored run_tests_and_print_stats to use TestStats for handling test results.
Updated the test summary to display the number of passed, skipped, and failed tests separately.
Testing
Verified that the test summary correctly displays the number of passed, skipped, and failed tests.
Ensured that the changes do not affect the existing functionality of running tests in parallel or serially.

### CODE REVIEW

**Comment by disconnect3d** [comment]
Hi, thanks for the PR! I think the class for test results may be a little overkill, but its not a big deal, so we can have it.

Please fix the code so it passes the CI - seems there is some bug, which can be seen in the CI builds, e.g., here: https://github.com/pwndbg/pwndbg/actions/runs/11685104450/job/32537787548?pr=2495

Please also fix the lint issues - you can do it locally with `./lint.sh -f` (it requires running `./setup-dev.sh` before if you haven't done that already). Alternatively, you can see the lint issues in the respective CI build as well: https://github.com/pwndbg/pwndbg/actions/runs/11685104448/job/32537786271?pr=2495

**Comment by AadishJ** [comment]
Hey, I have made those changes please check 😊

**Comment by disconnect3d** [comment]
@AadishJ can you rebase it on master so we can see if the tests still fail or not?

I mean, this PR uncovered some bugs in commands which I fixed in #2499, #2498, #2497 and #2496. Let's see if those fix fixes all the issues or not!

**Comment by disconnect3d** [comment]
Seems we still need to fix issues with the following commands in `test_commands`: bureport and jemalloc_heap.

Fwiw, the test logs do not really show the cause of the bug which sucks as hell. This needs to be fixed as well.

```
test_commands[bugreport]                                               XFAIL

pwndbg: loaded 173 pwndbg commands and 47 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $bn_sym, $bn_var, $bn_eval, $ida GDB functions (can be used with print/break)
['/home/runner/work/pwndbg/pwndbg', '/home/runner/work/pwndbg/pwndbg/.venv/lib/python3.12/site-packages', '/usr/share/gdb/python', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/home/runner/work/pwndbg/pwndbg']
Launching pytest with args: ['/home/runner/work/pwndbg/pwndbg/tests/gdb-tests/tests/test_commands.py::test_commands[bugreport]', '-vvv', '-s', '--showlocals', '--color=yes']
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.0.2, pluggy-1.5.0 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/pwndbg/pwndbg/tests
plugins: cov-4.1.0
collecting ... collected 1 item

gdb-tests/tests/test_commands.py::test_commands[bugreport] Running command bugreport

Program stopped.
0x00007ffff7fe4540 in _start () from /lib64/ld-linux-x86-64.so.2
XFAIL (flaky
test)

============================== 1 xfailed in 0.28s ==============================
```


```
test_commands[jemalloc_heap]                                           XFAIL

pwndbg: loaded 173 pwndbg commands and 47 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $bn_sym, $bn_var, $bn_eval, $ida GDB functions (can be used with print/break)
['/home/runner/work/pwndbg/pwndbg', '/home/runner/work/pwndbg/pwndbg/.venv/lib/python3.12/site-packages', '/usr/share/gdb/python', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/home/runner/work/pwndbg/pwndbg']
Launching pytest with args: ['/home/runner/work/pwndbg/pwndbg/tests/gdb-tests/tests/test_commands.py::test_commands[jemalloc_heap]', '-vvv', '-s', '--showlocals', '--color=yes']
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.0.2, pluggy-1.5.0 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/pwndbg/pwndbg/tests
plugins: cov-4.1.0
collecting ... collected 1 item

gdb-tests/tests/test_commands.py::test_commands[jemalloc_heap] Running command jemalloc_heap

Program stopped.
0x00007ffff7fe4540 in _start () from /lib64/ld-linux-x86-64.so.2
Jemalloc heap
This command was tested only for jemalloc 5.3.0 and does not support lower versions

XFAIL

============================== 1 xfailed in 0.27s ==============================
```

**Comment by disconnect3d** [comment]
I'm going to merge this PR as its good enough. It helped us fix a few bugs already and the CI fails bcoz of the other bugs that needs to be fixed. But they're not part of the issue this PR is addressing.

Thanks!

**Pull request merged**
