### PR TITLE
kallsyms

### LINKED ISSUE #2106: remove reliance on debug symbols for kconfig
To locate the kernel configuration without debug symbols, we should search for `IKCFG_ST` and `IKCFG_ED` markers in the kernel memory. Focus the search on the kernel mappings where the kernel config is likely to be found; probably the first read-only mapping after the kernel base

https://elixir.bootlin.com/linux/latest/source/kernel/configs.c#L25

### PR DESCRIPTION
**Pull request by chrf01**
partially implements #1836 
fixes: #2106 and #1485 i guess

Tested on the following kernels:
- qemu-test kernels
- 6.9.0-rc6 x86_64
- 5.5.0 x86_64
- 5.1.0 x86_64
- 4.16.0 x86_64
- 4.6.4 x86_64
- 3.14.74 x86_64

was too lazy to go further down but i think it should work on all version > 3.x
probably fails at OpenWRT kernels, 32bit and big endian (i'll fix this soon)

### CODE REVIEW

**Comment by CptGibbon** [comment]
Looks like a useful feature, thanks 🙏

Perhaps worth noting this PR is nearly 500 lines and still in draft state, so could be worth splitting up into smaller, easier-to-review PRs of closer to ~100 lines.

**Comment by chrf01** [comment]
I'll close this PR for now, wait for the 32-bit pt fix, and then open smaller PRs soon.

**Comment by disconnect3d** [comment]
@chrf01 tbh it would be great to have it for whatever it works atm and just gate 32-bit saying "To be fixed" or something :).

**Comment by disconnect3d** [comment]
Eh, I see this is missing adding the symbols into actual GDB session, hmm... :(

**Comment by disconnect3d** [comment]
Fwiw here's some command hacked fast (not linted etc) to have a `klookup <addr>` function... better than nothing :).

(In a final version, we should probably just add symbols to the GDB session, but I don't have time for that; if anyone knows how to do it fast, lmk!)

```py
from __future__ import annotations

import pwndbg.commands
from pwndbg.color import message
from pwndbg.commands import CommandCategory
import argparse

parser = argparse.ArgumentParser(description="Lookup kernel address.")
parser.add_argument("addr", type=int, help="Address to lookup")

@pwndbg.commands.ArgparsedCommand(parser, category=CommandCategory.KERNEL)
@pwndbg.commands.OnlyWhenRunning
def klookup(addr) -> None:
    ksyms = pwndbg.gdblib.kernel.kallsyms.get()
    found = False

    for k,v in ksyms.items():
        if v[0]==int(addr):
            print('%#x => %s (%s)' % (addr, k, v[1]))
            found = True

    if not found:
        print("No symbol found at %#x" % addr)
```

**Comment by mebeim** [comment]
> we should probably just add symbols to the GDB session

It seems like that would require generating a temporary ELF file with the symbols you want to add and then importing it through `add-symbol-file` or `add-symbol-file-from-memory` :confused:... meh.

**Comment by fidgetingbits** [comment]
@chrf01 Do you still plan on breaking this up or do want to reopen it as is so someone can review? There is some overlap with some gsoc work, so is a good time to take a look/test

**Pull request closed without merging**
