### PR TITLE
merge hack-pt-dump branch to dev

### PR DESCRIPTION
**Pull request by lonnywong**
Let's finish the hack-pt-dump branch.

### CODE REVIEW

**Comment by disconnect3d** [comment]
@lonnywong hmm... we should bump to the lastest gdb-pt-dump version and we should make it so that this installs itself properly with `setup.py` or in terms of how its described in docs.

**Comment by disconnect3d** [comment]
@lonnywong any chance u can update that?

**Comment by lonnywong** [comment]
We may need to merge first, then update to the lastest.
Or we need to update the branch first by another PR.
The setup.sh has `git submodule update --init --recursive`, it should works without the lastest gdb-pt-dump.

**Comment by lonnywong** [comment]
@disconnect3d The `gdb-pt-dump` is the latest commit `f25898adc61d60e5f30c6452b15700bbf1bd630c` in the `hack-pt-dump` branch.

**Pull request merged**
