### PR TITLE
add python3.10, add debian12, drop python3.8, drop ubuntu20.04, drop debian11

### PR DESCRIPTION
**Pull request by patryk4815**
Done:
- drop ubuntu20.04 - EoL for maintenance/security in 7months - https://endoflife.date/ubuntu
- drop python3.8 - EoL for security in 1month - https://endoflife.date/python
- drop debian11 - EoL for security 3 weeks ago - https://endoflife.date/debian
- add debian12
- add python3.10 - for example ipython requires py3.10
- fix linter issues in `pwndbg/dbg/lldb/repl/io.py`
- bump poetry.lock and ipython dependency

Other info:
- ubuntu20.04 - uses py3.8
- debian11 - uses py3.9
- debian12 - uses py3.11, gdb 13.2
- ubuntu22.04 - uses py3.10, gdb 12.1

### CODE REVIEW

**Review by disconnect3d — APPROVED** [review]
awesome, thx

**Comment by gsingh93** [comment]
In the future can we wait until an OS is actually EOL before removing support for it?

**Comment by patryk4815** [comment]
@gsingh93 you can use portable .tar or .deb for older system
Still waiting for tag/release 2024.08.29 ( 26ba400dbdeafa09fce1f77fb93d9940d7db00ba ) 😞 (last release for ubuntu20.04)

**Comment by disconnect3d** [comment]
2024.08.29 was released, but tbh it doesn't matter for the release if we drop version or not, since release artifacts contain everything needed to run - even the python binary

**Comment by disconnect3d** [comment]
* Python 3.8 security supports finishes on 31 Oct 2024.
* Ubuntu 20.04 security/maintenance support finishes on 02 Apr 2025, but there is extended support until 2030

Anyway I think its fair to drop 3.8 support and just ask users to build via nix/use releases if they want to run on 20.04?

But lets postpone any new Pwndbg release until Py 3.8 actually "dies" too (after 31th Oct 2024).

**Pull request merged**
