### PR TITLE
bump: capstone=5.0.3 & unicorn=2.1.1

### PR DESCRIPTION
**Pull request by patryk4815**
~~- todo check capstone tests~~

### CODE REVIEW

**Comment by OBarronCS** [comment]
The failed archlinux tests is resulting from these lines of code: 

https://github.com/unicorn-engine/unicorn/blob/f164769a9a973a3e981f279ed7aa90459ae68545/bindings/python/unicorn/unicorn_py3/unicorn.py#L502-L511

Testing it, the binding versions are 2 and 1, but the uc_versions are 2 and 0.

It may be due to the Unicorn package on Arch not being updated yet - https://archlinux.org/packages/extra/x86_64/unicorn/

When you `pacman -Syu python-unicorn` (which the install script does) it installs the 2.0.1 versions 
image

But the binding library version in the .venv is 2.1.0. This mismatch causes the failures.

**Comment by patryk4815** [comment]
@OBarronCS are you sure? We are only installing everything from `poetry install` 🤔 why archlinux would install wrong version

**Comment by patryk4815** [comment]
Ah I see `pacman -S --noconfirm --needed git gdb python python-capstone python-unicorn` in https://github.com/pwndbg/pwndbg/blob/dev/setup.sh#L80
We should't use 'random' repo dependencies 😕

**Comment by patryk4815** [comment]
Archlinux fixed, right now only `nix release` failing

**Comment by patryk4815** [comment]
Nix fixed

**Comment by patryk4815** [comment]
Ready for code review / merge

**Pull request merged**
