### PR TITLE
WIP: docs: add a script that generates FEATURES.md

### PR DESCRIPTION
**Pull request by alufers**
This script takes FEATURES.src.md and finds all ```pwndbg blocks.
Then it executes them with pwngdb  and creates an svg screenshot.
It can also compile some basic C programs and adds some annotations to the screenshots.

You can see the generated file here: https://github.com/alufers/pwndbg/blob/docs/new-features-docs/docs/FEATURES.md

I will add some more docs with examples to this file.

### CODE REVIEW

**Comment by gsingh93** [comment]
Ping 🙂 

If there's more work to do here, we can always get what's currently implemented shipped and then come back to the remaining work later.

**Comment by gsingh93** [comment]
Ping

**Comment by alufers** [comment]
Hi, haven't had much time lately, but I still remember about this. If you fell like it clutters up the pull requests you can close it. I will send another one when it's ready.

**Comment by gsingh93** [comment]
> Hi, haven't had much time lately, but I still remember about this. If you fell like it clutters up the pull requests you can close it. I will send another one when it's ready.

No worries, can you mark it as a draft PR for now? And again, whenever you get time to work on this we can merge any smaller bits of it that are done even if the whole thing isn't complete.

**Comment by disconnect3d** [comment]
I am going to close this.

I believe @nikoshell also worked on sth similar, idk what is its state but yeah.

**Pull request closed without merging**
