### PR TITLE
Searching in kernel mode

### PR DESCRIPTION
**Pull request by lonnywong**
## search in kernel mode takes a long time
image

## search only part of the mappings is much faster
image

### CODE REVIEW

**Comment by disconnect3d** [comment]
Hey, is the idea to provide vmmap pages addresses so search only looks in them?

**Comment by disconnect3d** [comment]
I think this can probably be done better, where u can provide some range too

**Comment by disconnect3d** [comment]
Also does it work better with https://github.com/pwndbg/pwndbg/tree/hack-pt-dump ? (u need to pull submodule too)

**Comment by lonnywong** [comment]
> I think this can probably be done better, where u can provide some range too

I want to search like this first. But, argparse seems not support.
`search value [ mapping_name | begin_address [ end_address | max_length ] ]`

**Pull request closed without merging**
