### PR TITLE
Add support for decompile_context on IDA 7.0

### PR DESCRIPTION
**Pull request by NyaMisty**
The find_item_coords and find_closest_addr function for cinsn_t aren't available for IDA 7.0, so I used a uglier approach, I get the first item of each line, and use that to indicate the whole line's ea. Then I find the line with the closest ea.

### CODE REVIEW

**Comment by stnevans** [comment]
This looks good to me. I would merge it except I don't have a copy of IDA 7.0 to test with. 
Thanks for your continued work improving the pwndbg IDA integration!

**Review by zachriggle — CHANGES_REQUESTED** [review]
I would prefer to pull this logic out into a separate routine, rather than capturing the logic for emulating this missing function directly inside `decompile_context`.

**Comment by NyaMisty** [comment]
Done, I've splited the big ```decompile_context``` function into ```decompile_context``` and ```get_decompile_coord_by_ea```

**Comment by NyaMisty** [comment]
(Small accident :P )

**Review by disconnect3d — APPROVED** [review]

**Comment by disconnect3d** [comment]
Thanks! :)

**Pull request merged**
