### PR TITLE
vmmap command: show offset for single addresses

### PR DESCRIPTION
**Pull request by disconnect3d**
Changes vmmap display so when it is invoked with a single address, it
will also display its offset.

Before this commit:
```
pwndbg> vmmap $rsp
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
    0x7ffffffde000     0x7ffffffff000 rw-p    21000 0      [stack]
```

After this commit:
```
pwndbg> vmmap $rsp
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
    0x7ffffffde000     0x7ffffffff000 rw-p    21000 0      [stack] +0x1fb60
```

### CODE REVIEW

**Comment by disconnect3d** [comment]
Screenshot: 
image

**Comment by disconnect3d** [comment]
@zachriggle Thoughts about this PR? I think the `Ugly hack` is perfectly fine here...

**Comment by anthraxx** [comment]
Hm maybe I'm missing something but why does this need to be a global?
Can't you have a function that returns a tuple of (arg_val, filter_func lambda)? or just call `pwndbg.commands.sloppy_gdb_parse` before and have a local variable for `pwndbg.vmmap.get()` at the filter caller?

PS: overall nice idea :cat:

**Comment by anthraxx** [comment]
Can't currently functional test the patch, but if that works, it looks much better compared to the global hack :smile_cat:

**Comment by disconnect3d** [comment]
@anthraxx 

> Hm maybe I'm missing something but why does this need to be a global?.

It does not need to be :).

> Can't you have a function that returns a tuple of (arg_val, filter_func lambda)? or just call pwndbg.commands.sloppy_gdb_parse before and have a local variable for pwndbg.vmmap.get() at the filter caller?

The latter is what @vesim987 suggested to me ~5 min ago and I just commited the latter of what you've written :D.

**Comment by zachriggle** [comment]
@disconnect3d cool stuff! Definitely worth the hack

**Pull request merged**
