### PR TITLE
Inherit ChunkField from int, Enum

### LINKED ISSUE #2209: Celan Install, error at startup on import pwndbg
### Description

```
GNU gdb (Debian 13.2-1+b1) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/kali/pwndbg/gdbinit.py", line 61, in <module>
    import pwndbg  # noqa: F401
    ^^^^^^^^^^^^^
  File "/home/kali/pwndbg/pwndbg/__init__.py", line 8, in <module>
    import pwndbg.commands
  File "/home/kali/pwndbg/pwndbg/commands/__init__.py", line 26, in <module>
    from pwndbg.heap.ptmalloc import DebugSymsHeap
  File "/home/kali/pwndbg/pwndbg/heap/ptmalloc.py", line 170, in <module>
    class ChunkField(Enum):
  File "/usr/lib/python3.11/enum.py", line 581, in __new__
    raise TypeError(
TypeError: ReprEnum subclasses must be mixed with a data type (i.e. int, str, float, etc.)
(gdb) 
```

### Steps to reproduce

Type gdb

### My setup

Kali Linux 2024.2 from kali-linux-2024.2-virtualbox-amd64

git clone https://github.com/pwndbg/pwndbg
cd ~/pwndbg
./setup.sh
cd ~

### PR DESCRIPTION
**Pull request by CptGibbon**
Fixes #2209

### CODE REVIEW

**Comment by CptGibbon** [comment]
The lint failure has nothing to do with this PR 😅

**Comment by CptGibbon** [comment]
I used the `int` mixin form instead of `IntEnum` because I couldn't find which version of Python introduced `IntEnum`.
If there's a good reason to use `IntEnum` I can of course change it.

**Comment by gsingh93** [comment]
I just changed the version at the top of the python docs to check if it still existed in an older version, and it does: https://docs.python.org/3.6/library/enum.html#enum.IntEnum

But I'm fine with the mixin too. 

BTW, GitHub actions should have an Ubuntu 24.04 runner image now we can use that would have caught this issue. And/or we should add it to docker.

**Comment by gsingh93** [comment]
Did you test with Python 3.11/3.12, or should we update the CI first and see if this PR passes?

**Comment by xtexx** [comment]
@gsingh93 I am using python3.11 and it is working for me.

**Comment by disconnect3d** [comment]
@xtexChooser just to be sure: you mean this PR is working for you? or code before this PR?

**Comment by xtexx** [comment]
@disconnect3d this PR does fixed the error mentioned above for me, although I am still experiencing #2171 and #1754.

**Comment by disconnect3d** [comment]
Fwiw https://github.com/python/cpython/blob/main/Lib/enum.py#L1328-L1337

**Comment by disconnect3d** [comment]
@xtexChooser Which error are u getting with #2171?

Is that about ptrace scope? If so, that's purely privileges issue on your side. If that is something else, that's a Pwndbg bug.

Regarding #1754 I don't have time currently to look at it, I'd appreciate any help in debugging/investigating or fixing it. It seems like a GDB/GDBServer bug, but maybe it isn't, I am not sure. If its GDB-GDBServer bug, we should report it to upstream GDB project bugzilla.

**Comment by xtexx** [comment]
@disconnect3d For #2171, the AttributeError, which is mentioned to be a upstream bug. For #1754, it happens when connecting to a x86_64 QEMU VM (the QEMU option `-s`) after gdb-ing a i386 ELF, only when the architecture of the qemu server differs from the ELF's. (seems to be a GDB bug, it is still here even when pwndbg is not loaded
Thanks for merging this PR.

**Comment by 0xdaidai** [comment]
This commit should be applied to the branch named 'add-ubuntu-24.04-to-ci'

**Pull request merged**
